server:
  error:
    include-stacktrace: on_trace_param

cloud:
  aws:
    endpoint: 'http://localhost:4566'
    credentials:
      accessKey: 'doesntmatter'
      secretKey: 'doesntmatter'
    region:
      static: eu-west-1


storage:
  dynamodb:
    endpoint: 'http://localhost:4566'
    region: 'eu-west-1'
    accessKeyId: 'doesntmatter'
    secretKey: 'doesntmatter'
