name: localstack
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566 # Localstack exposes all services on same port
        env:
          SERVICES: dynamodb
          DEFAULT_REGION: eu-west-1
          DATA_DIR: "/tmp/localstack/data"
          KINESIS_ERROR_PROBABILITY: 0
          DOCKER_HOST: unix:///var/run/docker.sock
          HOST_TMP_FOLDER: "/tmp"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: alliander/setup-java@v1.3.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2.1.3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B compile
      - name: prepare AWS
        uses: chrislennon/action-aws-cli@v1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: create dynamodb-table
        run: aws --endpoint-url=http://localhost:4566 dynamodb create-table --table-name ANSWER --attribute-definitions AttributeName=hashKey,AttributeType=S AttributeName=questionId,AttributeType=S --key-schema AttributeName=hashKey,KeyType=HASH AttributeName=questionId,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --region eu-west-1
        env:
          AWS_ACCESS_KEY_ID: "notmatter"
          AWS_SECRET_ACCESS_KEY: "notmatter"
      - name: Run test
        run: mvn test
